# Generated by Django 2.2.2 on 2019-06-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('mean', models.CharField(max_length=100)),
                ('sentence', models.CharField(max_length=100)),
                ('pron', models.CharField(max_length=100)),
                ('remind', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='ajs7270@naver.com', max_length=70)),
                ('dic', models.ManyToManyField(to='login.Dic')),
            ],
        ),
    ]
