# Generated by Django 2.2.2 on 2019-06-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('mean', models.CharField(max_length=100)),
                ('sentence', models.CharField(max_length=1000)),
                ('pron', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dic',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='dic',
            name='pron',
        ),
        migrations.RemoveField(
            model_name='dic',
            name='sentence',
        ),
        migrations.AddField(
            model_name='dic',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='full_memory_word',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='half_memory_word',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='dic',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.word'),
        ),
    ]
